/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/request-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Otp */
        post: operations["request_otp_api_v1_auth_request_otp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Otp */
        post: operations["verify_otp_api_v1_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rbac/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seed Rbac */
        post: operations["seed_rbac_api_v1_admin_rbac_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{account_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Account Roles */
        get: operations["list_account_roles_api_v1_admin_accounts__account_id__roles_get"];
        put?: never;
        /** Assign Account Roles */
        post: operations["assign_account_roles_api_v1_admin_accounts__account_id__roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{account_id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Account Permissions */
        get: operations["list_account_permissions_api_v1_admin_accounts__account_id__permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/access-grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Access Grants */
        get: operations["list_access_grants_api_v1_patients__patient_id__access_grants_get"];
        put?: never;
        /** Create Access Grant */
        post: operations["create_access_grant_api_v1_patients__patient_id__access_grants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/access-grants/{grant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Access Grant */
        delete: operations["revoke_access_grant_api_v1_patients__patient_id__access_grants__grant_id__delete"];
        options?: never;
        head?: never;
        /** Update Access Grant */
        patch: operations["update_access_grant_api_v1_patients__patient_id__access_grants__grant_id__patch"];
        trace?: never;
    };
    "/api/v1/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Logs */
        get: operations["list_audit_logs_api_v1_audit_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Patient */
        post: operations["create_patient_api_v1_patients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Patient */
        get: operations["get_my_patient_api_v1_patients_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update My Person */
        patch: operations["update_my_person_api_v1_patients_me_patch"];
        trace?: never;
    };
    "/api/v1/patients/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Patient */
        get: operations["get_patient_api_v1_patients__patient_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Patient Documents */
        get: operations["list_patient_documents_api_v1_patients__patient_id__documents_get"];
        put?: never;
        /** Create Document */
        post: operations["create_document_api_v1_patients__patient_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_api_v1_documents__document_id__versions_get"];
        put?: never;
        /** Create Version */
        post: operations["create_version_api_v1_documents__document_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Extractions */
        get: operations["list_extractions_api_v1_documents__document_id__extractions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_documents__document_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Document */
        get: operations["download_document_api_v1_documents__document_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/markdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Markdown */
        get: operations["get_document_markdown_api_v1_documents__document_id__markdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/canonical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Canonical */
        get: operations["get_document_canonical_api_v1_documents__document_id__canonical_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/encounters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Encounters */
        get: operations["list_encounters_api_v1_patients__patient_id__encounters_get"];
        put?: never;
        /** Create Encounter */
        post: operations["create_encounter_api_v1_patients__patient_id__encounters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/encounters/{encounter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Encounter */
        get: operations["get_encounter_api_v1_encounters__encounter_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Encounter */
        patch: operations["update_encounter_api_v1_encounters__encounter_id__patch"];
        trace?: never;
    };
    "/api/v1/encounters/{encounter_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Encounter Documents */
        get: operations["list_encounter_documents_api_v1_encounters__encounter_id__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessGrantCreate */
        AccessGrantCreate: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Organization Id */
            organization_id?: string | null;
            /**
             * Can View Documents
             * @default false
             */
            can_view_documents: boolean;
            /**
             * Can Upload Documents
             * @default false
             */
            can_upload_documents: boolean;
            /**
             * Can View Extractions
             * @default false
             */
            can_view_extractions: boolean;
            /**
             * Can View Analytics
             * @default false
             */
            can_view_analytics: boolean;
            /**
             * Can Create Encounters
             * @default false
             */
            can_create_encounters: boolean;
            /**
             * Can Edit Medical Data
             * @default false
             */
            can_edit_medical_data: boolean;
            access_reason?: components["schemas"]["AccessReason"] | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /** AccessGrantResponse */
        AccessGrantResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Organization Id */
            organization_id: string | null;
            /** Can View Documents */
            can_view_documents: boolean;
            /** Can Upload Documents */
            can_upload_documents: boolean;
            /** Can View Extractions */
            can_view_extractions: boolean;
            /** Can View Analytics */
            can_view_analytics: boolean;
            /** Can Create Encounters */
            can_create_encounters: boolean;
            /** Can Edit Medical Data */
            can_edit_medical_data: boolean;
            status: components["schemas"]["GrantStatus"];
            /**
             * Granted At
             * Format: date-time
             */
            granted_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Granted By Account Id */
            granted_by_account_id: string | null;
            access_reason: components["schemas"]["AccessReason"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AccessGrantUpdate */
        AccessGrantUpdate: {
            /** Can View Documents */
            can_view_documents?: boolean | null;
            /** Can Upload Documents */
            can_upload_documents?: boolean | null;
            /** Can View Extractions */
            can_view_extractions?: boolean | null;
            /** Can View Analytics */
            can_view_analytics?: boolean | null;
            /** Can Create Encounters */
            can_create_encounters?: boolean | null;
            /** Can Edit Medical Data */
            can_edit_medical_data?: boolean | null;
            access_reason?: components["schemas"]["AccessReason"] | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /**
         * AccessReason
         * @enum {string}
         */
        AccessReason: "treatment" | "consultation" | "diagnosis" | "follow_up";
        /** AccountRoleAssignRequest */
        AccountRoleAssignRequest: {
            /** Role Codes */
            role_codes: string[];
        };
        /** AccountRolesResponse */
        AccountRolesResponse: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Roles */
            roles: components["schemas"]["RoleResponse"][];
        };
        /**
         * AccountStatus
         * @enum {string}
         */
        AccountStatus: "pending" | "active" | "blocked" | "deleted";
        /**
         * AuditAction
         * @enum {string}
         */
        AuditAction: "LOGIN" | "LOGOUT" | "VIEW_PATIENT" | "VIEW_MEDICAL_RECORD" | "VIEW_DOCUMENT" | "DOWNLOAD_DOCUMENT" | "UPLOAD_DOCUMENT" | "CREATE_ENCOUNTER" | "UPDATE_ENCOUNTER" | "GRANT_ACCESS" | "REVOKE_ACCESS" | "VIEW_ANALYTICS";
        /** AuditLogResponse */
        AuditLogResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Actor Account Id */
            actor_account_id: string | null;
            action: components["schemas"]["AuditAction"];
            /** Resource Type */
            resource_type: string;
            /** Resource Id */
            resource_id: string | null;
            /** Patient Id */
            patient_id: string | null;
            /** Ip Address */
            ip_address: string;
            /** User Agent */
            user_agent: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_create_document_api_v1_patients__patient_id__documents_post */
        Body_create_document_api_v1_patients__patient_id__documents_post: {
            /** Upload */
            upload: string;
            /** @default other */
            document_type: components["schemas"]["DocumentType"];
            /**
             * Title
             * @default
             */
            title: string;
            /** Encounter Id */
            encounter_id?: string | null;
        };
        /** Body_create_version_api_v1_documents__document_id__versions_post */
        Body_create_version_api_v1_documents__document_id__versions_post: {
            /** Upload */
            upload: string;
            /** @default other */
            document_type: components["schemas"]["DocumentType"];
            /**
             * Title
             * @default
             */
            title: string;
        };
        /**
         * CanonicalDataResponse
         * @description Persisted canonical data (latest succeeded extraction) for a document.
         *
         *     ``data`` mirrors ``document_extractions.data`` and includes the canonical
         *     object plus ``canonical_key`` / ``structured_key``.
         */
        CanonicalDataResponse: {
            /** Schema Name */
            schema_name: string;
            /** Schema Version */
            schema_version: string;
            /** Confidence */
            confidence?: number | null;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /**
         * CanonicalResponse
         * @description Inline parsed canonical JSON + rendered markdown for a document version.
         *
         *     ``canonical.json`` is the single source of truth from the ai-worker; the
         *     rendered markdown is the deterministic Python `structured.md` view.
         */
        CanonicalResponse: {
            /** Canonical */
            canonical?: {
                [key: string]: unknown;
            } | null;
            /** Canonical Key */
            canonical_key?: string | null;
            /** Structured Markdown */
            structured_markdown?: string | null;
            /**
             * Has Canonical
             * @default false
             */
            has_canonical: boolean;
        };
        /** DocumentExtractionResponse */
        DocumentExtractionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Version Id */
            document_version_id: string | null;
            /** Schema Name */
            schema_name: string;
            /** Schema Version */
            schema_version: string;
            status: components["schemas"]["ExtractionStatus"];
            /** Confidence */
            confidence: number | null;
            /** Data */
            data: {
                [key: string]: unknown;
            } | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** DocumentResponse */
        DocumentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Medical Record Id
             * Format: uuid
             */
            medical_record_id: string;
            /** Encounter Id */
            encounter_id: string | null;
            document_type: components["schemas"]["DocumentType"];
            /** Title */
            title: string;
            /** Original Filename */
            original_filename: string;
            /** Mime Type */
            mime_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Storage Key */
            storage_key: string;
            status: components["schemas"]["DocumentStatus"];
            /** Document Date */
            document_date?: string | null;
            /** Uploaded By Account Id */
            uploaded_by_account_id: string | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "pending" | "uploaded" | "processing" | "completed" | "failed" | "deleted";
        /**
         * DocumentType
         * @enum {string}
         */
        DocumentType: "lab_result" | "doctor_report" | "prescription" | "discharge_summary" | "imaging_report" | "referral" | "medical_certificate" | "other";
        /** DocumentVersionResponse */
        DocumentVersionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Version */
            version: number;
            /** S3 Key */
            s3_key: string;
            /** Mime Type */
            mime_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Checksum */
            checksum: string | null;
            /** Created By Account Id */
            created_by_account_id: string | null;
            /** Created At */
            created_at: string | null;
        };
        /** DownloadUrlResponse */
        DownloadUrlResponse: {
            /** Download Url */
            download_url: string;
            /** Expires In */
            expires_in: number;
        };
        /** EncounterCreate */
        EncounterCreate: {
            /** @default consultation */
            type: components["schemas"]["EncounterType"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Reason */
            reason?: string | null;
            /** Summary */
            summary?: string | null;
        };
        /** EncounterResponse */
        EncounterResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Medical Record Id
             * Format: uuid
             */
            medical_record_id: string;
            /** Specialist Id */
            specialist_id: string | null;
            /** Organization Id */
            organization_id: string | null;
            type: components["schemas"]["EncounterType"];
            status: components["schemas"]["EncounterStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Ended At
             * Format: date-time
             */
            ended_at: string;
            /** Reason */
            reason: string | null;
            /** Summary */
            summary: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EncounterStatus
         * @enum {string}
         */
        EncounterStatus: "scheduled" | "in_progress" | "completed" | "cancelled" | "no_show";
        /**
         * EncounterType
         * @enum {string}
         */
        EncounterType: "consultation" | "follow_up" | "procedure" | "admission" | "telemedicine" | "other";
        /** EncounterUpdate */
        EncounterUpdate: {
            status?: components["schemas"]["EncounterStatus"] | null;
            /** Ended At */
            ended_at?: string | null;
            /** Summary */
            summary?: string | null;
        };
        /**
         * ExtractionStatus
         * @enum {string}
         */
        ExtractionStatus: "pending" | "extracting" | "succeeded" | "failed";
        /**
         * GrantStatus
         * @enum {string}
         */
        GrantStatus: "active" | "revoked" | "expired";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobResponse */
        JobResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Version Id */
            document_version_id: string | null;
            job_type: components["schemas"]["ProcessingJobType"];
            status: components["schemas"]["ProcessingJobStatus"];
            /** Attempts */
            attempts: number;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** PatientCreateRequest */
        PatientCreateRequest: {
            person?: components["schemas"]["PersonUpdate"] | null;
        };
        /** PatientResponse */
        PatientResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            person: components["schemas"]["PersonResponse"];
            /**
             * Medical Record Id
             * Format: uuid
             */
            medical_record_id: string;
            status: components["schemas"]["PatientStatus"];
        };
        /**
         * PatientStatus
         * @enum {string}
         */
        PatientStatus: "active" | "inactive";
        /** PermissionResponse */
        PermissionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** PersonResponse */
        PersonResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Date Of Birth */
            date_of_birth: string | null;
            sex: components["schemas"]["Sex"] | null;
            /** City */
            city: string | null;
            /** Profession */
            profession: string | null;
            /** Height */
            height: number | null;
            /** Weight */
            weight: number | null;
            /** Age */
            readonly age: number | null;
        };
        /** PersonUpdate */
        PersonUpdate: {
            /** Name */
            name?: string | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            sex?: components["schemas"]["Sex"] | null;
            /** City */
            city?: string | null;
            /** Profession */
            profession?: string | null;
            /** Height */
            height?: number | null;
            /** Weight */
            weight?: number | null;
        };
        /**
         * ProcessingJobStatus
         * @enum {string}
         */
        ProcessingJobStatus: "queued" | "running" | "succeeded" | "retrying" | "failed";
        /**
         * ProcessingJobType
         * @enum {string}
         */
        ProcessingJobType: "pdf_conversion" | "ai_extraction" | "embedding";
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
            /** Device Id */
            device_id?: string | null;
            /** Platform */
            platform?: string | null;
            /** App Version */
            app_version?: string | null;
        };
        /** RequestOtpRequest */
        RequestOtpRequest: {
            /**
             * Identity
             * @description email address or phone number
             */
            identity: string;
        };
        /** RoleResponse */
        RoleResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /**
         * Sex
         * @enum {string}
         */
        Sex: "male" | "female" | "unspecified";
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            status: components["schemas"]["AccountStatus"];
            /** Is Subscribed */
            is_subscribed: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyOtpRequest */
        VerifyOtpRequest: {
            /** Identity */
            identity: string;
            /**
             * Code
             * @description 6-digit one-time code
             */
            code: string;
            /** Device Id */
            device_id?: string | null;
            /** Platform */
            platform?: string | null;
            /** App Version */
            app_version?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    request_otp_api_v1_auth_request_otp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestOtpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_otp_api_v1_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOtpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    seed_rbac_api_v1_admin_rbac_seed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_account_roles_api_v1_admin_accounts__account_id__roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRolesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_account_roles_api_v1_admin_accounts__account_id__roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountRoleAssignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRolesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_account_permissions_api_v1_admin_accounts__account_id__permissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_access_grants_api_v1_patients__patient_id__access_grants_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessGrantResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_access_grant_api_v1_patients__patient_id__access_grants_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessGrantCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessGrantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_access_grant_api_v1_patients__patient_id__access_grants__grant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
                grant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessGrantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_access_grant_api_v1_patients__patient_id__access_grants__grant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
                grant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessGrantUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessGrantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_logs_api_v1_audit_logs_get: {
        parameters: {
            query?: {
                patient_id?: string | null;
                actor_id?: string | null;
                action?: components["schemas"]["AuditAction"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_patient_api_v1_patients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatientCreateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_patient_api_v1_patients_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponse"];
                };
            };
        };
    };
    update_my_person_api_v1_patients_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_api_v1_patients__patient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_patient_documents_api_v1_patients__patient_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_api_v1_patients__patient_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_document_api_v1_patients__patient_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_documents__document_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_version_api_v1_documents__document_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_version_api_v1_documents__document_id__versions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_extractions_api_v1_documents__document_id__extractions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentExtractionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_documents__document_id__jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_document_api_v1_documents__document_id__download_get: {
        parameters: {
            query?: {
                version_id?: string | null;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_markdown_api_v1_documents__document_id__markdown_get: {
        parameters: {
            query?: {
                version_id?: string | null;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_canonical_api_v1_documents__document_id__canonical_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_encounters_api_v1_patients__patient_id__encounters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_encounter_api_v1_patients__patient_id__encounters_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EncounterCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_encounter_api_v1_encounters__encounter_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_encounter_api_v1_encounters__encounter_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EncounterUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_encounter_documents_api_v1_encounters__encounter_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
