from enum import Enum

"""
Access / audit-domain enums.
"""


class GrantStatus(str, Enum):
    ACTIVE = "active"
    REVOKED = "revoked"
    EXPIRED = "expired"


class AccessReason(str, Enum):
    TREATMENT = "treatment"
    CONSULTATION = "consultation"
    DIAGNOSIS = "diagnosis"
    FOLLOW_UP = "follow_up"


class AuditAction(str, Enum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    VIEW_PATIENT = "VIEW_PATIENT"
    VIEW_MEDICAL_RECORD = "VIEW_MEDICAL_RECORD"
    VIEW_DOCUMENT = "VIEW_DOCUMENT"
    DOWNLOAD_DOCUMENT = "DOWNLOAD_DOCUMENT"
    UPLOAD_DOCUMENT = "UPLOAD_DOCUMENT"
    CREATE_ENCOUNTER = "CREATE_ENCOUNTER"
    UPDATE_ENCOUNTER = "UPDATE_ENCOUNTER"
    GRANT_ACCESS = "GRANT_ACCESS"
    REVOKE_ACCESS = "REVOKE_ACCESS"
    VIEW_ANALYTICS = "VIEW_ANALYTICS"
    ORGANIZATION_UPDATED = "ORGANIZATION_UPDATED"
    ORGANIZATION_CREATED = "ORGANIZATION_CREATED"
    ORGANIZATION_ADMIN_ADDED = "ORGANIZATION_ADMIN_ADDED"
    ORGANIZATION_BRANCH_CREATED = "ORGANIZATION_BRANCH_CREATED"
    ORGANIZATION_BRANCH_UPDATED = "ORGANIZATION_BRANCH_UPDATED"
    ORGANIZATION_BRANCH_DEACTIVATED = "ORGANIZATION_BRANCH_DEACTIVATED"
    ORGANIZATION_LICENSE_CREATED = "ORGANIZATION_LICENSE_CREATED"
    ORGANIZATION_LICENSE_UPDATED = "ORGANIZATION_LICENSE_UPDATED"
    ORGANIZATION_LICENSE_DEACTIVATED = "ORGANIZATION_LICENSE_DEACTIVATED"
    API_KEY_CREATED = "API_KEY_CREATED"
    API_KEY_REVOKED = "API_KEY_REVOKED"
    API_KEY_AUTH_FAILED = "API_KEY_AUTH_FAILED"
    INTEGRATION_DOCUMENT_UPLOADED = "INTEGRATION_DOCUMENT_UPLOADED"
    INTEGRATION_BATCH_CREATED = "INTEGRATION_BATCH_CREATED"
    ORGANIZATION_SCHEMA_CREATED = "ORGANIZATION_SCHEMA_CREATED"
    ORGANIZATION_SCHEMA_UPDATED = "ORGANIZATION_SCHEMA_UPDATED"
    ORGANIZATION_SCHEMA_PUBLISHED = "ORGANIZATION_SCHEMA_PUBLISHED"


class PatientAccessGrantNotFoundError(Exception):
    """An access grant does not exist for the given patient and id."""


class PatientAccessDeniedError(Exception):
    """The account has no access right to the patient medical data."""